title: Brett L. Schuchert
description: Collected works and current thoughts
twitter_username: schuchert
theme: jekyll-theme-midnight
highlight: rouge
github_username: schuchert
layout: kramdown
markdown: kramdown
kramdown:
  parse_block_html: true
plugins_dir:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-relative-links
  - html-proofer
baseurl: "/"
url: "https://schuchert.github.io"
google_analytics: UA-122965859-1
google_site_verification: 1j-H9WhaWm5G7bpQh3pDqRgdlQLGl30wWdIU9Q6nZwY
repository: schuchert/schuchert.github.io
github: [metadata]
exclude: [Gemfile,Gemfile.lock]
include: [favico.ico]
future: true
